name: Backend Workflow

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-backend:
    runs-on: [self-hosted, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Backend
        run: |
          echo " Building backend..."
