name: Frontend Workflow

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-frontend:
    runs-on: [self-hosted, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Frontend
        run: |
          echo " Building frontend..."
